name: Build Python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - 3.9.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pyenv and Python version
      uses: gabrielfalcao/pyenv-action@v18
      with:
        default: "${{ matrix.python }}"
        command: |
          # 安装 pyenv 和指定版本的 Python
          pyenv install ${{ matrix.python }}
          pyenv global ${{ matrix.python }}
          python --version

    - name: Run clean.sh and build.sh
      run: |
        chmod +x clean.sh
        ./clean.sh
        ARCH=arm64 ANDROID_API=21 ./build.sh

    - name: Save build artifacts
      run: |
        mkdir build_artifacts
        cp -r build/* build_artifacts/
        echo ::set-output name=build_artifacts_path::build_artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Deploy to output branch
      run: |
        # Move to the build directory
        cd ${{ needs.build.outputs.build_artifacts_path }}
    
        # Create a new branch if it doesn't exist
        git checkout -B output
    
        # Add and commit the changes
        git add .
        git commit -m "Deploy to output branch"
    
        # Push to the output branch
        git push origin output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
